version: "3.1"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin 
      MYSQL_DATABASE: tg 
      MYSQL_USER: admin 
      MYSQL_PASSWORD: admin 
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "--password=admin"]
      interval: 10s       # 健康检查的时间间隔
      timeout: 5s         # 每次健康检查的超时时间
      retries: 50          # 最大重试次数，超过后标记为不健康
      start_period: 30s   # 容器启动后等待的时间，避免数据库初始化过程中的错误
  scraper:
    image: scraper:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: tg
      SQLALCHEMY_POOL_SIZE: 10
      NOSTR_PRIV_KEY: nsec1ufnus6pju578ste3v90xd5m2decpuzpql2295m3sknqcjzyys9ls0qlc85
      NOSTR_RELAY_URIS: wss://relay.damus.io